apiVersion: v1
kind: Service
metadata:
  name: pod-metadata-service
spec:
  selector:
    app: pod-metadata
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      #nodePort: 30080
  type: NodePort
